#+SETUPFILE: ../setup.org
#+OPTIONS: toc:nil
#+Title: RBM cumulants: Numerical approximation
#+Author: Tor Erlend Fjelde

As described earlier, the second order interactions between $v_{j_1}$ and $v_{j_2}$ can be obtained by
\begin{equation}\label{eq:second-order-interacts-full}
\sum_{n=2}^{\infty} \frac{\kappa_{\mu}^{(n)}}{n!} \bigg[ \Big( W_{\mu j_1} + W_{\mu j_2} \Big)^n - \Big( W_{\mu j_1} \Big)^n - \Big(W_{\mu j_2}\Big)^n \bigg]
\end{equation}
with
\begin{equation}\label{eq:kappa}
\kappa_{\mu}^{(n + 1)} = \sigma^{(n)}(b_{\mu}) = \sum_{k=1}^{n} \big( -1 \big)^{k - 1} A_{n, k-1} \sigma (b_{\mu})^k \big( 1 - \sigma(b_{\mu}) \big)^{n + 1 - k}
\end{equation}
where the expression for the n-th order derivative of the sigmoid function $\sigma$ can be found in cite:minai1993derivatives. The Eulerian numbers can be computed explicitly using
\begin{equation*}
A_{n, m} = \sum_{k=0}^{m} \big( -1 \big)^k {n + 1 \choose k} \big( m + 1 - k \big)^n
\end{equation*}

At first, we tried computing Eq. ref:eq:second-order-interacts-full numerically with a truncation of the series. For this to be a good approximation, we would need the $\kappa_{\mu}^{(n)} / n!$ to decrease in magnitude at a greater rate than the increase of $\tilde{W}_{\mu, j_1, j_2}^{(n)} = \big( W_{\mu j_1} + W_{\mu j_2} \big)^n - \big( W_{\mu j_1} \big)^n - \big( W_{\mu j_2} \big)^n$. Otherwise the higher-order terms have non-vanishing contributions to the series, making it difficult, if not impossible, to approximate the series using a truncation of the series.

In Table ref:table:weights-and-kappas we can clearly see that this is not the case for Eq. ref:eq:second-order-interacts-full. Taking the second order interaction between $v_0$ and $v_{50}$ as an example, we observe that the higher order terms have non-vanishing contributions; in fact, the resulting terms are still increasing with $n = 30$. As the behavior is consistent even for small $n$, we can confidently rule out numerical errors as the sole source of this behavior, and therefore we cannot necessarily expect to be able to approximate this series numerically using a truncation.[fn:1] This emphasizes the importance of the closed-form expression derived earlier.

#+name: table:weights-and-kappas
#+caption: Obtained from weights of trained RBM with $64$ visible and hidden units on $64 \times 64$ Ising model with $T = 1.8$.
| $n$ | $\sum_{\mu} \tilde{W}_{\mu, 0, 50} \cdot \ \kappa_{\mu}^{(n)} / n!$ |
|-----+--------------------------------------------|
|   2 |                               1.437377e+00 |
|   3 |                               2.430778e+00 |
|   4 |                              -2.753242e+00 |
|   5 |                              -9.941742e+00 |
|   6 |                              -1.686830e+00 |
|   7 |                               2.707638e+01 |
|   8 |                               3.090465e+01 |
|   9 |                              -5.172942e+01 |
|  10 |                              -1.449903e+02 |
|  11 |                               1.981997e+01 |
|  12 |                               4.791551e+02 |
|  13 |                               4.108461e+02 |
|  14 |                              -1.148652e+03 |
|  15 |                              -2.499102e+03 |
|  16 |                               1.296267e+03 |
|  17 |                               9.660143e+03 |
|  18 |                               5.415548e+03 |
|  19 |                              -2.723113e+04 |
|  20 |                              -4.618300e+04 |
|  21 |                               4.614661e+04 |
|  22 |                               2.061784e+05 |
|  23 |                               5.184063e+04 |
|  24 |                              -6.623404e+05 |
|  25 |                              -8.620642e+05 |
|  26 |                               1.426449e+06 |
|  27 |                               4.494383e+06 |
|  28 |                              -3.701061e+05 |
|  29 |                              -1.622603e+07 |
|  30 |                              -1.550309e+07 |

bibliographystyle:unsrt
bibliography:../../references.bib

* Footnotes

[fn:1] We also verified the computation of the Eulerian numbers using the identity $\sum_{k=0}^{n-1} A_{n, k} = n!$. Longs were used for all integer computations, converting to 128-floating points only when needed.
